# Generated by Django 2.2.9 on 2020-01-21 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g', models.CharField(max_length=255)),
                ('c1', models.FloatField()),
                ('c2', models.FloatField()),
                ('c3', models.FloatField()),
                ('c4', models.FloatField()),
                ('c5', models.FloatField()),
                ('c6', models.FloatField()),
                ('c7', models.FloatField()),
                ('c8', models.FloatField()),
                ('c9', models.FloatField()),
                ('c10', models.FloatField()),
                ('c11', models.FloatField()),
                ('c12', models.FloatField()),
                ('ahorro_deuda', models.FloatField()),
                ('ingreso', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('index_exp', models.IntegerField()),
                ('folio', models.CharField(max_length=255)),
                ('ingreso', models.FloatField()),
                ('fe', models.IntegerField()),
                ('np', models.IntegerField()),
                ('gasto', models.FloatField()),
                ('ingreso_disp', models.FloatField()),
                ('ptge_gasto', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=255)),
                ('inga_hd', models.FloatField()),
                ('fe', models.FloatField()),
                ('persona', models.FloatField()),
                ('npersonas', models.FloatField()),
                ('edad', models.FloatField()),
                ('ingreso_hd', models.FloatField()),
                ('ingreso_pc', models.FloatField()),
            ],
        ),
    ]
