# Generated by Django 2.2.9 on 2019-12-30 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('index_exp', models.IntegerField()),
                ('folio', models.CharField(max_length=255)),
                ('ingreso', models.FloatField()),
                ('fe', models.IntegerField()),
                ('np', models.IntegerField()),
                ('gasto', models.FloatField()),
                ('ingreso_disp', models.FloatField()),
                ('ptge_gasto', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='DataManager',
        ),
    ]
